"""localization.py — словарь переводов для GUI Pixie (дашборд, онбординг, настройки).

При смене языка в настройках все тексты интерфейса переключаются на выбранный язык
без перезапуска приложения. Ключи словаря — логические идентификаторы текста.
"""
from __future__ import annotations

from typing import Any

# Полный словарь локализации UI — для каждого языка все тексты дашборда,
# настроек и онбординга. Ключи: en, ru, es, zh, hi, fr, de.
# Если ключа нет — используется английский fallback.

UI_LOCALIZATION: dict[str, dict[str, str]] = {
    "en": {
        # --- Dashboard (app_shell.py) ---
        "window_title": "{name} — Home",
        "dark_btn": "🌙 Dark",
        "light_btn": "☀ Light",
        "subtitle_ready": "Your AI voice assistant is ready.",
        "pro_active": "⭐ Pixie Pro — active",
        "free_plan": "Free plan",
        "details_line": "Voice: {voice}   ·   Personality: {personality}\nProject: {project}",
        "start_btn": "▶  Start Pixie",
        "settings_btn": "⚙  Settings",
        "manage_sub": "⭐  Manage subscription",
        "get_pro": "⭐  Get Pixie Pro",
        "pro_hint": "Pro unlocks full Unreal Engine control: actors, Blueprints, camera & more.",
        "exit_btn": "Exit",
        # --- Settings window (QuickSettingsWindow в onboarding.py) ---
        "settings_title": "Settings",
        "settings_subtitle": "Edit any of your saved preferences below and hit Save.",
        "close_btn": "Close",
        "save_btn": "💾 Save",
        "saved_label": "✓ Saved",

        # --- Labels для секций настроек ---
        "language_label": "Language",
        "theme_label": "Theme",
        "ai_provider_label": "AI provider",
        "api_key_label": "API key",
        "show_key": "Show",
        "assistant_name_label": "Assistant name",
        "voice_label": "Voice",
        "personality_label": "Personality",
        "project_type_label": "Project type",
        "ue_folder_label": "UE project folder",
        "browse_btn": "Browse…",
        "gdd_label": "Game Design Document",
        "gdd_attached": "✅ Attached: {name}",
        "gdd_none": "No document attached",
        "gdd_upload_btn": "Upload…",
        "gdd_success": "✅ Document attached successfully",
        "gdd_fail": "❌ Failed to copy file: {error}",

        # --- Onboarding wizard ---
        "lang_step_title": "🌍 Choose your language",
        "lang_step_subtitle": "Pick the language Pixie will speak and use in its interface. You can change this later anytime from Settings.",
        "lang_picker_label": "Language",
        "welcome_title": "Welcome to Pixie 👋",
        "welcome_subtitle": "Let's set your assistant up in a couple of minutes. No config files, no manual editing — just answer a few questions.",
        "theme_picker_label": "Choose your theme:",
        "api_step_title": "Connect your AI",
        "api_step_subtitle": "Pick an AI provider and paste your API key. Pixie currently runs on Google Gemini Live — support for more providers is coming soon.",
        "api_provider_label": "AI provider",
        "api_key_label_onboard": "API key",
        "api_key_placeholder": "Paste your API key here",
        "show_key_check": "Show key",
        "api_key_required": "Please paste your Gemini API key to continue.",
        "identity_title": "Make it yours",
        "identity_subtitle": "Name your assistant, pick a voice and a personality, and tell Pixie what kind of project you're building.",
        "name_label": "Assistant name",
        "name_placeholder": "Pixie",
        "name_required": "Give your assistant a name.",
        "voice_label_onboard": "Voice",
        "personality_label_onboard": "Personality",
        "project_label_onboard": "What are you building?",
        "ue_step_title": "Unreal Engine setup (optional)",
        "ue_step_subtitle": "If you're using Unreal Engine, point Pixie to your project and enable Python Remote Execution. Not using UE? Just skip this step.",
        "ue_folder_label_onboard": "UE project folder",
        "ue_help_text": "ℹ  In Unreal Editor: Edit → Project Settings → Plugins → Python → enable \"Enable Remote Execution\". Restart the editor afterwards.",
        "gdd_label_onboard": "Game Design Document (optional, PDF or TXT)",
        "gdd_label_display": "No document attached",
        "summary_title": "All set! 🎉",
        "summary_subtitle": "Pixie is ready to go. You can revisit any of these settings later from the Settings button on the home screen.",
        "back_btn": "← Back",
        "next_btn": "Next →",
        "finish_btn": "Finish",
        "language_row": "Language",
        "assistant_row": "Assistant name",
        "voice_row": "Voice",
        "personality_row": "Personality",
        "project_row": "Project",
        "ue_path_row": "UE project path",
        "gdd_path_row": "Game Design Document",
        "not_set": "— (not set)",
        "not_attached": "— (not attached)",
    },

    "ru": {
        "window_title": "{name} — Домой",
        "dark_btn": "🌙 Тёмная",
        "light_btn": "☀ Светлая",
        "subtitle_ready": "Ваш AI-голосовой ассистент готов.",
        "pro_active": "⭐ Pixie Pro — активна",
        "free_plan": "Бесплатная версия",
        "details_line": "Голос: {voice}   ·   Характер: {personality}\nПроект: {project}",
        "start_btn": "▶  Запустить Pixie",
        "settings_btn": "⚙  Настройки",
        "manage_sub": "⭐  Управление подпиской",
        "get_pro": "⭐  Получить Pixie Pro",
        "pro_hint": "Pro открывает полный контроль над Unreal Engine: акторы, Blueprint, камера и другое.",
        "exit_btn": "Выход",
        "settings_title": "Настройки",
        "settings_subtitle": "Измените любые сохранённые параметры ниже и нажмите Сохранить.",
        "close_btn": "Закрыть",
        "save_btn": "💾 Сохранить",
        "saved_label": "✓ Сохранено",
        "language_label": "Язык",
        "theme_label": "Тема",
        "ai_provider_label": "AI-провайдер",
        "api_key_label": "API-ключ",
        "show_key": "Показать",
        "assistant_name_label": "Имя ассистента",
        "voice_label": "Голос",
        "personality_label": "Характер",
        "project_type_label": "Тип проекта",
        "ue_folder_label": "Папка проекта UE",
        "browse_btn": "Обзор…",
        "gdd_label": "Документ игры (GDD)",
        "gdd_attached": "✅ Прикреплён: {name}",
        "gdd_none": "Документ не прикреплён",
        "gdd_upload_btn": "Загрузить…",
        "gdd_success": "✅ Документ успешно прикреплён",
        "gdd_fail": "❌ Не удалось скопировать файл: {error}",
        "lang_step_title": "🌍 Выберите язык",
        "lang_step_subtitle": "Выберите язык, на котором Pixie будет говорить и отображать интерфейс. Язык можно сменить позже в Настройках.",
        "lang_picker_label": "Язык",
        "welcome_title": "Добро пожаловать в Pixie 👋",
        "welcome_subtitle": "Давайте настроим вашего ассистента за пару минут. Никаких конфиг-файлов — просто ответьте на несколько вопросов.",
        "theme_picker_label": "Выберите тему:",
        "api_step_title": "Подключите AI",
        "api_step_subtitle": "Выберите AI-провайдера и вставьте API-ключ. Pixie работает на Google Gemini Live — поддержка других провайдеров скоро появится.",
        "api_provider_label": "AI-провайдер",
        "api_key_label_onboard": "API-ключ",
        "api_key_placeholder": "Вставьте ваш API-ключ сюда",
        "show_key_check": "Показать ключ",
        "api_key_required": "Пожалуйста, вставьте ваш Gemini API-ключ для продолжения.",
        "identity_title": "Сделайте своим",
        "identity_subtitle": "Дайте имя ассистенту, выберите голос и характер, и расскажите Pixie, над каким проектом вы работаете.",
        "name_label": "Имя ассистента",
        "name_placeholder": "Pixie",
        "name_required": "Дайте имя вашему ассистенту.",
        "voice_label_onboard": "Голос",
        "personality_label_onboard": "Характер",
        "project_label_onboard": "Над чем вы работаете?",
        "ue_step_title": "Настройка Unreal Engine (опционально)",
        "ue_step_subtitle": "Если вы используете Unreal Engine, укажите путь к проекту и включите Python Remote Execution. Не используете UE? Просто пропустите этот шаг.",
        "ue_folder_label_onboard": "Папка проекта UE",
        "ue_help_text": "ℹ  В редакторе Unreal: Edit → Project Settings → Plugins → Python → включите \"Enable Remote Execution\". После этого перезапустите редактор.",
        "gdd_label_onboard": "Документ игры (опционально, PDF или TXT)",
        "gdd_label_display": "Документ не прикреплён",
        "summary_title": "Всё готово! 🎉",
        "summary_subtitle": "Pixie готова к работе. Вы можете изменить любые настройки позже из экрана Настроек на главном экране.",
        "back_btn": "← Назад",
        "next_btn": "Далее →",
        "finish_btn": "Завершить",
        "language_row": "Язык",
        "assistant_row": "Имя ассистента",
        "voice_row": "Голос",
        "personality_row": "Характер",
        "project_row": "Проект",
        "ue_path_row": "Путь к проекту UE",
        "gdd_path_row": "Документ игры (GDD)",
        "not_set": "— (не указано)",
        "not_attached": "— (не прикреплён)",
    },

    "es": {
        "window_title": "{name} — Inicio",
        "dark_btn": "🌙 Oscuro",
        "light_btn": "☀ Claro",
        "subtitle_ready": "Tu asistente de voz AI está listo.",
        "pro_active": "⭐ Pixie Pro — activo",
        "free_plan": "Plan gratuito",
        "details_line": "Voz: {voice}   ·   Personalidad: {personality}\nProyecto: {project}",
        "start_btn": "▶  Iniciar Pixie",
        "settings_btn": "⚙  Ajustes",
        "manage_sub": "⭐  Gestionar suscripción",
        "get_pro": "⭐  Obtener Pixie Pro",
        "pro_hint": "Pro desbloquea el control completo de Unreal Engine: actores, Blueprints, cámara y más.",
        "exit_btn": "Salir",
        "settings_title": "Ajustes",
        "settings_subtitle": "Edite sus preferencias guardadas abajo y pulse Guardar.",
        "close_btn": "Cerrar",
        "save_btn": "💾 Guardar",
        "saved_label": "✓ Guardado",
        "language_label": "Idioma",
        "theme_label": "Tema",
        "ai_provider_label": "Proveedor AI",
        "api_key_label": "Clave API",
        "show_key": "Mostrar",
        "assistant_name_label": "Nombre del asistente",
        "voice_label": "Voz",
        "personality_label": "Personalidad",
        "project_type_label": "Tipo de proyecto",
        "ue_folder_label": "Carpeta del proyecto UE",
        "browse_btn": "Examinar…",
        "gdd_label": "Documento del juego (GDD)",
        "gdd_attached": "✅ Adjunto: {name}",
        "gdd_none": "Sin documento adjunto",
        "gdd_upload_btn": "Subir…",
        "gdd_success": "✅ Documento adjuntado correctamente",
        "gdd_fail": "❌ Error al copiar el archivo: {error}",
        "lang_step_title": "🌍 Elija su idioma",
        "lang_step_subtitle": "Seleccione el idioma que Pixie usará para hablar y mostrar la interfaz. Puede cambiarlo después en Ajustes.",
        "lang_picker_label": "Idioma",
        "welcome_title": "Bienvenido a Pixie 👋",
        "welcome_subtitle": "Configuremos su asistente en un par de minutos. Sin archivos de configuración — solo responda unas preguntas.",
        "theme_picker_label": "Elija su tema:",
        "api_step_title": "Conecte su AI",
        "api_step_subtitle": "Seleccione un proveedor AI y pegue su clave API. Pixie funciona con Google Gemini Live — pronto habrá más proveedores.",
        "api_provider_label": "Proveedor AI",
        "api_key_label_onboard": "Clave API",
        "api_key_placeholder": "Pegue su clave API aquí",
        "show_key_check": "Mostrar clave",
        "api_key_required": "Por favor, pegue su clave de Gemini API para continuar.",
        "identity_title": "Hágalo suyo",
        "identity_subtitle": "Nombre a su asistente, elija una voz y personalidad, y dígale a Pixie qué tipo de proyecto está creando.",
        "name_label": "Nombre del asistente",
        "name_placeholder": "Pixie",
        "name_required": "Ponga un nombre a su asistente.",
        "voice_label_onboard": "Voz",
        "personality_label_onboard": "Personalidad",
        "project_label_onboard": "¿Qué está construyendo?",
        "ue_step_title": "Configuración de Unreal Engine (opcional)",
        "ue_step_subtitle": "Si usa Unreal Engine, señale el proyecto y active Python Remote Execution. ¿No usa UE? Simplemente salte este paso.",
        "ue_folder_label_onboard": "Carpeta del proyecto UE",
        "ue_help_text": "ℹ  En el Editor Unreal: Edit → Project Settings → Plugins → Python → active \"Enable Remote Execution\". Reinicie el editor después.",
        "gdd_label_onboard": "Documento del juego (opcional, PDF o TXT)",
        "gdd_label_display": "Sin documento adjunto",
        "summary_title": "¡Todo listo! 🎉",
        "summary_subtitle": "Pixie está lista. Puede revisar estos ajustes más tarde desde el botón Ajustes en la pantalla de inicio.",
        "back_btn": "← Atrás",
        "next_btn": "Siguiente →",
        "finish_btn": "Finalizar",
        "language_row": "Idioma",
        "assistant_row": "Nombre del asistente",
        "voice_row": "Voz",
        "personality_row": "Personalidad",
        "project_row": "Proyecto",
        "ue_path_row": "Ruta del proyecto UE",
        "gdd_path_row": "Documento del juego (GDD)",
        "not_set": "— (no establecido)",
        "not_attached": "— (no adjuntado)",
    },

    "zh": {
        "window_title": "{name} — 主页",
        "dark_btn": "🌙 深色",
        "light_btn": "☀ 浅色",
        "subtitle_ready": "您的AI语音助手已就绪。",
        "pro_active": "⭐ Pixie Pro — 已激活",
        "free_plan": "免费版",
        "details_line": "语音: {voice}   ·   个性: {personality}\n项目: {project}",
        "start_btn": "▶ 启动Pixie",
        "settings_btn": "⚙ 设置",
        "manage_sub": "⭐ 管理订阅",
        "get_pro": "⭐ 获取Pixie Pro",
        "pro_hint": "Pro版解锁完整的Unreal Engine控制：Actor、蓝图、摄像机等。",
        "exit_btn": "退出",
        "settings_title": "设置",
        "settings_subtitle": "编辑您的偏好设置，然后点击保存。",
        "close_btn": "关闭",
        "save_btn": "💾 保存",
        "saved_label": "✓ 已保存",
        "language_label": "语言",
        "theme_label": "主题",
        "ai_provider_label": "AI提供商",
        "api_key_label": "API密钥",
        "show_key": "显示",
        "assistant_name_label": "助手名称",
        "voice_label": "语音",
        "personality_label": "个性",
        "project_type_label": "项目类型",
        "ue_folder_label": "UE项目文件夹",
        "browse_btn": "浏览…",
        "gdd_label": "游戏设计文档",
        "gdd_attached": "✅ 已附加: {name}",
        "gdd_none": "未附加文档",
        "gdd_upload_btn": "上传…",
        "gdd_success": "✅ 文档附加成功",
        "gdd_fail": "❌ 复制文件失败: {error}",
        "lang_step_title": "🌍 选择语言",
        "lang_step_subtitle": "选择Pixie使用的语言。您可以稍后在设置中更改。",
        "lang_picker_label": "语言",
        "welcome_title": "欢迎使用Pixie 👋",
        "welcome_subtitle": "只需几分钟即可设置您的助手。无需配置文件，只需回答几个问题。",
        "theme_picker_label": "选择主题:",
        "api_step_title": "连接AI",
        "api_step_subtitle": "选择AI提供商并粘贴API密钥。Pixie目前运行在Google Gemini Live上。",
        "api_provider_label": "AI提供商",
        "api_key_label_onboard": "API密钥",
        "api_key_placeholder": "在此粘贴您的API密钥",
        "show_key_check": "显示密钥",
        "api_key_required": "请粘贴您的Gemini API密钥以继续。",
        "identity_title": "个性化设置",
        "identity_subtitle": "为您的助手命名，选择语音和个性，并告诉Pixie您正在开发什么类型的项目。",
        "name_label": "助手名称",
        "name_placeholder": "Pixie",
        "name_required": "请为您的助手命名。",
        "voice_label_onboard": "语音",
        "personality_label_onboard": "个性",
        "project_label_onboard": "您正在构建什么？",
        "ue_step_title": "Unreal Engine设置（可选）",
        "ue_step_subtitle": "如果您使用Unreal Engine，请指向您的项目并启用Python Remote Execution。不使用UE？跳过此步骤。",
        "ue_folder_label_onboard": "UE项目文件夹",
        "ue_help_text": "ℹ 在Unreal编辑器中: Edit → Project Settings → Plugins → Python → 启用 \"Enable Remote Execution\"。之后重启编辑器。",
        "gdd_label_onboard": "游戏设计文档（可选，PDF或TXT）",
        "gdd_label_display": "未附加文档",
        "summary_title": "全部就绪！🎉",
        "summary_subtitle": "Pixie已准备就绪。您可以稍后从主页的设置按钮重新访问这些设置。",
        "back_btn": "← 返回",
        "next_btn": "下一步 →",
        "finish_btn": "完成",
        "language_row": "语言",
        "assistant_row": "助手名称",
        "voice_row": "语音",
        "personality_row": "个性",
        "project_row": "项目",
        "ue_path_row": "UE项目路径",
        "gdd_path_row": "游戏设计文档",
        "not_set": "—（未设置）",
        "not_attached": "—（未附加）",
    },

    "hi": {
        "window_title": "{name} — होम",
        "dark_btn": "🌙 डार्क",
        "light_btn": "☀ लाइट",
        "subtitle_ready": "आपका AI वॉयस असिस्टेंट तैयार है।",
        "pro_active": "⭐ Pixie Pro — सक्रिय",
        "free_plan": "फ्री प्लान",
        "details_line": "आवाज़: {voice}   ·   व्यक्तित्व: {personality}\nप्रोजेक्ट: {project}",
        "start_btn": "▶  Pixie शुरू करें",
        "settings_btn": "⚙  सेटिंग्स",
        "manage_sub": "⭐  सब्सक्रिप्शन प्रबंधित करें",
        "get_pro": "⭐  Pixie Pro प्राप्त करें",
        "pro_hint": "Pro अनलॉक करता है पूर्ण Unreal Engine नियंत्रण: एक्टर, ब्लूप्रिंट, कैमरा और अधिक।",
        "exit_btn": "बाहर जाएं",
        "settings_title": "सेटिंग्स",
        "settings_subtitle": "अपनी सहेजी गई प्राथमिकताओं को संपादित करें और सेव पर क्लिक करें।",
        "close_btn": "बंद करें",
        "save_btn": "💾 सेव करें",
        "saved_label": "✓ सेव हो गया",
        "language_label": "भाषा",
        "theme_label": "थीम",
        "ai_provider_label": "AI प्रदाता",
        "api_key_label": "API कुंजी",
        "show_key": "दिखाएं",
        "assistant_name_label": "सहायक का नाम",
        "voice_label": "आवाज़",
        "personality_label": "व्यक्तित्व",
        "project_type_label": "प्रोजेक्ट प्रकार",
        "ue_folder_label": "UE प्रोजेक्ट फ़ोल्डर",
        "browse_btn": "ब्राउज़ करें…",
        "gdd_label": "गेम डिज़ाइन दस्तावेज़",
        "gdd_attached": "✅ संलग्न: {name}",
        "gdd_none": "कोई दस्तावेज़ संलग्न नहीं",
        "gdd_upload_btn": "अपलोड करें…",
        "gdd_success": "✅ दस्तावेज़ सफलतापूर्वक संलग्न हुआ",
        "gdd_fail": "❌ फ़ाइल कॉपी करने में विफल: {error}",
        "lang_step_title": "🌍 अपनी भाषा चुनें",
        "lang_step_subtitle": "वह भाषा चुनें जिसमें Pixie बोलेगा और इंटरफ़ेस दिखाएगा। आप इसे बाद中 सेटिंग्स में बदल सकते हैं।",
        "lang_picker_label": "भाषा",
        "welcome_title": "Pixie में आपका स्वागत है 👋",
        "welcome_subtitle": "आइए कुछ मिनटوں میں आपके सहायक को सेट करें। कोई कॉन्फ़िग फ़ाइल नहीं — बस कुछ सवालों के जवाब दें।",
        "theme_picker_label": "अपनी थीम चुनें:",
        "api_step_title": "अपना AI कनेक्ट करें",
        "api_step_subtitle": "एक AI प्रदाता चुनें और अपनी API कुंजी पेस्ट करें। Pixie वर्तमान में Google Gemini Live पर चलता है।",
        "api_provider_label": "AI प्रदाता",
        "api_key_label_onboard": "API कुंजी",
        "api_key_placeholder": "अपनी API कुंजी यहाँ पेस्ट करें",
        "show_key_check": "कुंजी दिखाएं",
        "api_key_required": "कृपया जारी रखने के लिए अपनी Gemini API कुंजी पेस्ट करें।",
        "identity_title": "इसे अपना बनाएं",
        "identity_subtitle": "अपने सहायक को नाम दें, एक आवाज़ और व्यक्तित्व चुनें, और Pixie को बताएं कि आप किस तरह का प्रोजेक्ट बना रहे हैं।",
        "name_label": "सहायक का नाम",
        "name_placeholder": "Pixie",
        "name_required": "अपने सहायक को एक नाम दें।",
        "voice_label_onboard": "आवाज़",
        "personality_label_onboard": "व्यक्तित्व",
        "project_label_onboard": "आप क्या बना रहे हैं?",
        "ue_step_title": "Unreal Engine सेटअप (वैकल्पिक)",
        "ue_step_subtitle": "यदि आप Unreal Engine का उपयोग कर रहे हैं, तो अपने प्रोजेक्ट की ओर इशारा करें और Python Remote Execution सक्षम करें। UE का उपयोग नहीं कर रहे? इस चरण को छोड़ें।",
        "ue_folder_label_onboard": "UE प्रोजेक्ट फ़ोल्डर",
        "ue_help_text": "ℹ  Unreal Editor में: Edit → Project Settings → Plugins → Python → \"Enable Remote Execution\" सक्षम करें। उसके बाद एडिटर को पुनरारंभ करें।",
        "gdd_label_onboard": "गेम डिज़ाइन दस्तावेज़ (वैकल्पिक, PDF या TXT)",
        "gdd_label_display": "कोई दस्तावेज़ संलग्न नहीं",
        "summary_title": "सब तैयार है! 🎉",
        "summary_subtitle": "Pixie तैयार है। आप होम स्क्रीन पर सेटिंग्स बटन से बाद में इन सेटिंग्स पर वापस आ सकते हैं।",
        "back_btn": "← पीछे",
        "next_btn": "आगे →",
        "finish_btn": "समाप्त",
        "language_row": "भाषा",
        "assistant_row": "सहायक का नाम",
        "voice_row": "आवाज़",
        "personality_row": "व्यक्तित्व",
        "project_row": "प्रोजेक्ट",
        "ue_path_row": "UE प्रोजेक्ट पथ",
        "gdd_path_row": "गेम डिज़ाइन दस्तावेज़",
        "not_set": "— (सेट नहीं है)",
        "not_attached": "— (संलग्न नहीं)",
    },

    "fr": {
        "window_title": "{name} — Accueil",
        "dark_btn": "🌙 Sombre",
        "light_btn": "☀ Clair",
        "subtitle_ready": "Votre assistant vocal IA est prêt.",
        "pro_active": "⭐ Pixie Pro — actif",
        "free_plan": "Gratuit",
        "details_line": "Voix: {voice}   ·   Personnalité: {personality}\nProjet: {project}",
        "start_btn": "▶  Démarrer Pixie",
        "settings_btn": "⚙  Paramètres",
        "manage_sub": "⭐  Gérer l'abonnement",
        "get_pro": "⭐  Obtenir Pixie Pro",
        "pro_hint": "Pro débloque le contrôle complet d'Unreal Engine : acteurs, Blueprints, caméra et plus.",
        "exit_btn": "Quitter",
        "settings_title": "Paramètres",
        "settings_subtitle": "Modifiez vos préférences enregistrées ci-dessous et cliquez sur Enregistrer.",
        "close_btn": "Fermer",
        "save_btn": "💾 Enregistrer",
        "saved_label": "✓ Enregistré",
        "language_label": "Langue",
        "theme_label": "Thème",
        "ai_provider_label": "Fournisseur IA",
        "api_key_label": "Clé API",
        "show_key": "Afficher",
        "assistant_name_label": "Nom de l'assistant",
        "voice_label": "Voix",
        "personality_label": "Personnalité",
        "project_type_label": "Type de projet",
        "ue_folder_label": "Dossier du projet UE",
        "browse_btn": "Parcourir…",
        "gdd_label": "Document de conception du jeu",
        "gdd_attached": "✅ Joint : {name}",
        "gdd_none": "Aucun document joint",
        "gdd_upload_btn": "Télécharger…",
        "gdd_success": "✅ Document joint avec succès",
        "gdd_fail": "❌ Échec de la copie du fichier : {error}",
        "lang_step_title": "🌍 Choisissez votre langue",
        "lang_step_subtitle": "Choisissez la langue que Pixie utilisera pour parler et afficher l'interface. Vous pouvez la changer plus tard dans Paramètres.",
        "lang_picker_label": "Langue",
        "welcome_title": "Bienvenue sur Pixie 👋",
        "welcome_subtitle": "Configurons votre assistant en quelques minutes. Pas de fichiers de configuration — répondez simplement à quelques questions.",
        "theme_picker_label": "Choisissez votre thème :",
        "api_step_title": "Connectez votre IA",
        "api_step_subtitle": "Choisissez un fournisseur d'IA et collez votre clé API. Pixie fonctionne actuellement avec Google Gemini Live.",
        "api_provider_label": "Fournisseur IA",
        "api_key_label_onboard": "Clé API",
        "api_key_placeholder": "Collez votre clé API ici",
        "show_key_check": "Afficher la clé",
        "api_key_required": "Veuillez coller votre clé API Gemini pour continuer.",
        "identity_title": "Personnalisez",
        "identity_subtitle": "Nommez votre assistant, choisissez une voix et une personnalité, et dites à Pixie quel type de projet vous créez.",
        "name_label": "Nom de l'assistant",
        "name_placeholder": "Pixie",
        "name_required": "Donnez un nom à votre assistant.",
        "voice_label_onboard": "Voix",
        "personality_label_onboard": "Personnalité",
        "project_label_onboard": "Que construisez-vous ?",
        "ue_step_title": "Configuration d'Unreal Engine (optionnel)",
        "ue_step_subtitle": "Si vous utilisez Unreal Engine, pointez vers votre projet et activez Python Remote Execution. Vous n'utilisez pas UE ? Ignorez cette étape.",
        "ue_folder_label_onboard": "Dossier du projet UE",
        "ue_help_text": "ℹ  Dans l'éditeur Unreal : Edit → Project Settings → Plugins → Python → activez \"Enable Remote Execution\". Redémarrez l'éditeur ensuite.",
        "gdd_label_onboard": "Document de conception du jeu (optionnel, PDF ou TXT)",
        "gdd_label_display": "Aucun document joint",
        "summary_title": "Tout est prêt ! 🎉",
        "summary_subtitle": "Pixie est prête. Vous pouvez revoir ces paramètres plus tard depuis le bouton Paramètres sur l'écran d'accueil.",
        "back_btn": "← Retour",
        "next_btn": "Suivant →",
        "finish_btn": "Terminer",
        "language_row": "Langue",
        "assistant_row": "Nom de l'assistant",
        "voice_row": "Voix",
        "personality_row": "Personnalité",
        "project_row": "Projet",
        "ue_path_row": "Chemin du projet UE",
        "gdd_path_row": "Document de conception du jeu",
        "not_set": "— (non défini)",
        "not_attached": "— (non joint)",
    },

    "de": {
        "window_title": "{name} — Start",
        "dark_btn": "🌙 Dunkel",
        "light_btn": "☀ Hell",
        "subtitle_ready": "Ihr KI-Sprachassistent ist bereit.",
        "pro_active": "⭐ Pixie Pro — aktiv",
        "free_plan": "Kostenlos",
        "details_line": "Stimme: {voice}   ·   Persönlichkeit: {personality}\nProjekt: {project}",
        "start_btn": "▶  Pixie starten",
        "settings_btn": "⚙  Einstellungen",
        "manage_sub": "⭐  Abonnement verwalten",
        "get_pro": "⭐  Pixie Pro holen",
        "pro_hint": "Pro schaltet die volle Unreal Engine-Steuerung frei: Actors, Blueprints, Kamera und mehr.",
        "exit_btn": "Beenden",
        "settings_title": "Einstellungen",
        "settings_subtitle": "Bearbeiten Sie Ihre gespeicherten Einstellungen unten und klicken Sie auf Speichern.",
        "close_btn": "Schließen",
        "save_btn": "💾 Speichern",
        "saved_label": "✓ Gespeichert",
        "language_label": "Sprache",
        "theme_label": "Design",
        "ai_provider_label": "KI-Anbieter",
        "api_key_label": "API-Schlüssel",
        "show_key": "Anzeigen",
        "assistant_name_label": "Assistentenname",
        "voice_label": "Stimme",
        "personality_label": "Persönlichkeit",
        "project_type_label": "Projekttyp",
        "ue_folder_label": "UE-Projektordner",
        "browse_btn": "Durchsuchen…",
        "gdd_label": "Spielentwurfsdokument",
        "gdd_attached": "✅ Angehängt: {name}",
        "gdd_none": "Kein Dokument angehängt",
        "gdd_upload_btn": "Hochladen…",
        "gdd_success": "✅ Dokument erfolgreich angehängt",
        "gdd_fail": "❌ Fehler beim Kopieren der Datei: {error}",
        "lang_step_title": "🌍 Sprache wählen",
        "lang_step_subtitle": "Wählen Sie die Sprache, die Pixie sprechen und in der Oberfläche verwenden soll. Sie können sie später in den Einstellungen ändern.",
        "lang_picker_label": "Sprache",
        "welcome_title": "Willkommen bei Pixie 👋",
        "welcome_subtitle": "Lassen Sie uns Ihren Assistenten in wenigen Minuten einrichten. Keine Konfigurationsdateien — beantworten Sie einfach ein paar Fragen.",
        "theme_picker_label": "Wählen Sie Ihr Design:",
        "api_step_title": "Verbinden Sie Ihre KI",
        "api_step_subtitle": "Wählen Sie einen KI-Anbieter und fügen Sie Ihren API-Schlüssel ein. Pixie läuft derzeit auf Google Gemini Live.",
        "api_provider_label": "KI-Anbieter",
        "api_key_label_onboard": "API-Schlüssel",
        "api_key_placeholder": "Fügen Sie Ihren API-Schlüssel hier ein",
        "show_key_check": "Schlüssel anzeigen",
        "api_key_required": "Bitte fügen Sie Ihren Gemini-API-Schlüssel ein, um fortzufahren.",
        "identity_title": "Passen Sie es an",
        "identity_subtitle": "Geben Sie Ihrem Assistenten einen Namen, wählen Sie eine Stimme und Persönlichkeit und sagen Sie Pixie, an welcher Art von Projekt Sie arbeiten.",
        "name_label": "Assistentenname",
        "name_placeholder": "Pixie",
        "name_required": "Geben Sie Ihrem Assistenten einen Namen.",
        "voice_label_onboard": "Stimme",
        "personality_label_onboard": "Persönlichkeit",
        "project_label_onboard": "Was bauen Sie?",
        "ue_step_title": "Unreal Engine Einrichtung (optional)",
        "ue_step_subtitle": "Wenn Sie Unreal Engine verwenden, zeigen Sie auf Ihr Projekt und aktivieren Sie Python Remote Execution. Sie nutzen UE nicht? Überspringen Sie diesen Schritt.",
        "ue_folder_label_onboard": "UE-Projektordner",
        "ue_help_text": "ℹ  Im Unreal Editor: Edit → Project Settings → Plugins → Python → aktivieren Sie \"Enable Remote Execution\". Starten Sie den Editor danach neu.",
        "gdd_label_onboard": "Spielentwurfsdokument (optional, PDF oder TXT)",
        "gdd_label_display": "Kein Dokument angehängt",
        "summary_title": "Alles bereit! 🎉",
        "summary_subtitle": "Pixie ist bereit. Sie können diese Einstellungen später über die Schaltfläche Einstellungen auf dem Startbildschirm aufrufen.",
        "back_btn": "← Zurück",
        "next_btn": "Weiter →",
        "finish_btn": "Fertigstellen",
        "language_row": "Sprache",
        "assistant_row": "Assistentenname",
        "voice_row": "Stimme",
        "personality_row": "Persönlichkeit",
        "project_row": "Projekt",
        "ue_path_row": "UE-Projektpfad",
        "gdd_path_row": "Spielentwurfsdokument",
        "not_set": "— (nicht festgelegt)",
        "not_attached": "— (nicht angehängt)",
    },
}


def _(key: str, lang: str = "en", **fmt_kwargs: Any) -> str:
    """Получить локализованный текст по ключу.

    Args:
        key: Ключ текста (например 'start_btn', 'settings_btn').
        lang: Код языка ('en', 'ru', 'es', 'zh', 'hi', 'fr', 'de').
        **fmt_kwargs: Параметры для .format() — подстановка {name}, {voice} и т.д.

    Returns:
        Локализованный текст. Если ключ не найден — возвращает сам key.
    """
    lang_dict = UI_LOCALIZATION.get(lang, UI_LOCALIZATION["en"])
    text = lang_dict.get(key, UI_LOCALIZATION["en"].get(key, key))
    if fmt_kwargs:
        try:
            text = text.format(**fmt_kwargs)
        except KeyError:
            pass
    return text